{
    "name": "Estandard - Dissenys",
    "summary": """Dissenys genèrics Batista10""",
    "author": "Batista10",
    "website": "https://www.batista10.cat",
    "category": "Personalization",
    "version": "13.0.1.1.2",
    "depends": [
        "base",
        "account_payment_partner",
        "sale",
        "sale_order_report_product_image",
        "stock",
        "state_original_name",
        "sale_management",
        "l10n_es_partner",
        "l10n_es",
    ],
    "license": "AGPL-3",
    "application": True,
    "data": [
        "views/debrand_odoo_mail.xml",
        "views/pressupost_batista.xml",
        "views/report_pressupost_batista.xml",
        "views/factura_batista.xml",
        "views/report_factura_batista.xml",
        "views/comanda_batista.xml",
        "views/report_comanda_batista.xml",
        "views/pressupost_st_batista.xml",
        "views/report_pressupost_st_batista.xml",
        "views/show_product_image.xml",
        "views/proforma_batista.xml",
        "views/report_proforma_batista.xml",
        "views/entrega_batista.xml",
        "views/report_entrega_batista.xml",
        "views/comanda_compra_batista.xml",
        "views/report_comanda_compra_batista.xml",
        "data/account.payment.method.csv",
    ],
}
