{
    "name": "Estandard - Dissenys",
    "summary": """Dissenys genèrics Batista10""",
    "author": "Batista10",
    "website": "https://www.batista10.cat",
    "category": "Personalization",
    "version": "17.0.1.2.0",
    "depends": [
        "base",
        "account_payment_partner",
        "sale",
        "sale_order_report_product_image",
        "stock",
        "state_original_name",
        "sale_management",
        "l10n_es_partner",
        "l10n_es_partner_mercantil",
    ],
    "license": "AGPL-3",
    "application": True,
    "data": [
        "report/pressupost_batista.xml",
        "report/report_pressupost_batista.xml",
        "report/factura_batista.xml",
        "report/report_factura_batista.xml",
        "report/comanda_batista.xml",
        "report/report_comanda_batista.xml",
        "report/pressupost_st_batista.xml",
        "report/report_pressupost_st_batista.xml",
        "report/proforma_batista.xml",
        "report/report_proforma_batista.xml",
        "report/entrega_batista.xml",
        "report/report_entrega_batista.xml",
        "data/account.payment.method.csv",
        "views/config_settings_view.xml",
        "views/show_product_image.xml",
    ],
}
