{
    "name": "Plantilles d'email Estandard",
    "summary": """Plantilles d'email genèriques Batista10""",
    "author": "Batista10",
    "website": "https://www.batista10.cat",
    "category": "Personalization",
    "version": "16.0.1.4.3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "l10n_es_partner",
        "Dissenys_generics",
    ],
    "license": "AGPL-3",
    "application": True,
    "data": [
        "views/debrand_odoo_mail.xml",
        "views/email_factura.xml",
        "views/email_factura_impagada.xml",
        "views/email_comanda.xml",
        "views/email_pressupost.xml",
        "views/email_proforma.xml",
    ],
}
