{
    "name": "Batista10 - Purchases",
    "summary": """Personalització de compres Batista10""",
    "author": "Batista10",
    "website": "https://www.batista10.cat",
    "category": "Personalization",
    "version": "18.0.1.0.2",
    "depends": [
        "base",
        "purchase",
        "field_encryption",
        "contacts",
        "l10n_es_partner",
        "l10n_es_partner_mercantil",
        "b10_mail",
        "b10_settings_hub",
    ],
    "license": "AGPL-3",
    "application": True,
    "data": [
        "security/security.xml",
        "report/B10_purchase_order_report.xml",
        "report/B10_purchase_order.xml",
        "report/B10_purchase_quotation_report.xml",
        "report/B10_purchase_quotation.xml",
        "views/b10_supplier_platform.xml",
        "views/B10_purchase_quotation_email.xml",
        "views/B10_purchase_order_email.xml",
    ],
}
